apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: NetHaus
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "https://github.com/haihhdev/IoTweb-devops.git"
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
