apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-ui
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/haidonglethqb/my-chatbot-repo.git'
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
