apiVersion: apps/v1
kind: Deployment
metadata:
  name: nethaus
  labels:
    app: nethaus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nethaus
  template:
    metadata:
      labels:
        app: nethaus
    spec:
      containers:


        - name: nethaus
          image: haichuthqb/chatbot-ui:3e68d801aa8df5a32a494699acf5cccae4b46598


          ports:
            - containerPort: 80