apiVersion: apps/v1
kind: Deployment
metadata:
  name: nethaus
  labels:
    app: nethaus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nethaus
  template:
    metadata:
      labels:
        app: nethaus
    spec:
      containers:


        - name: nethaus
          image: haichuthqb/chatbot-ui:991b0547d4f6ed91159855aedd7386a81a4f617e


          ports:
            - containerPort: 80