apiVersion: apps/v1
kind: Deployment
metadata:
  name: NetHaus
  labels:
    app: NetHaus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: NetHaus
  template:
    metadata:
      labels:
        app: NetHaus
    spec:
      containers:

        - name: NetHaus
          image: haichuthqb/chatbot-ui:b4eea8b7532cc57ade3c0da5f9990f3dea24bce8

          ports:
            - containerPort: 80