name: Delete Monitoring (Prometheus & Grafana)

on:
  workflow_dispatch: # Chạy tay trên GitHub Actions

jobs:
  delete-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name chatbot-cluster

      - name: Uninstall Prometheus & Grafana
        run: |
          helm uninstall kube-prometheus-stack -n monitoring || true
          kubectl delete namespace monitoring --ignore-not-found
